export const MAX_MAP_CODE_LENGTH = 400_000;
export const MAX_MAP_CODE_PLACEMENTS = 100_000;
export const MAX_MAP_OPERATIONS = 50_000;
export const MAX_MAP_CODE_SCENE_OPERATIONS = MAX_MAP_OPERATIONS;
export const MAX_MAP_GRASS_LAYERS = 512;
export const MAX_MAP_GUIDE_POINTS = 16_384;

export const MAP_CODE_DISCOVERY_TIMEOUT_MS = 15_000;
export const MAP_CODE_FINAL_TIMEOUT_MS = 30_000;
export const MAP_CODE_REPLAY_TIMEOUT_MS = 45_000;
